services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
    env_file:
      - .env
    networks:
      - default
      - coolify

networks:
  coolify:
    external: true
